Documentation work, removed unneeded models
discipl/flinteditor-mps pull request #198
Opened 2022-07-14 12:47 UTC by TristanAlbers

- Removed unneeded models
- Added info to dev guide
- Documented typesystem and constraint

2022-07-19 14:17 UTC, TristanAlbers commented
When remaking models (if needed) be aware of deprecated links, Flintmodel UML not complete

2022-07-20 07:20 UTC, TristanAlbers commented on docs/TYPESYSTEM_CONSTRAINS.md
> +Acts have certain properties which must be filled. The properties are `actor`,`object` and `recipient`. When one of these is not filled in an error will be generated.
Documentation about implemenation put inside codebase [in this pullrequest](https://github.com/discipl/flinteditor-mps/pull/202)

2022-08-02 08:50 UTC, blackstardlb requested changes
Add Titles to each diagram 

```
title Act Model
````

2022-08-02 08:50 UTC, blackstardlb commented on docs/uml/flintmodel-model.puml
> +interface "Flint.structure.IFlintModel" <INamedConcept>
include these methods in IFlintModel

![image](https://user-images.githubusercontent.com/15971736/182332466-5179027a-9937-48b5-9c63-fb8e36c7502b.png)

2022-08-02 08:50 UTC, blackstardlb commented on docs/uml/ihassources-model.puml
> +"Flint.structure.FlintSource" : text : string
text is deprecated

2022-08-02 08:52 UTC, blackstardlb commented
I've added installLocalGitHook task to gradle which after run once will install a precommit hook that auto generates the uml diagram renders

2022-08-02 13:45 UTC, blackstardlb approved these changes
lgtm 👍

2022-08-02 13:51 UTC, merged